import React from 'react';
import { Link } from 'react-router-dom';
import { BookOpen, FolderOpen, FileText, GraduationCap, ArrowUpRight, Download, Bookmark, MessageSquare, Eye, ArrowRight, ShieldCheck, Inbox, Check } from 'lucide-react';
import { useApp } from '../context';
import { resourcePath, messagePath, categoryNames, formatBytes, formatDate, fileLabel } from '../utils';
export function BrandMark({size=38}) {return <svg width={size} height={size} viewBox="0 0 52 58" fill="none" aria-hidden="true"><g stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M5 53V15h42v38M10 53V20h32v33M18 53V36c0-8 8-12 8-12s8 4 8 12v17M23 53V37c0-4 3-6 3-6s3 2 3 6v16M2 15h48M8 10l18-7 18 7M15 10h22M5 6v5M47 6v5M26 1v3M2 53h48M13 20v8M39 20v8"/><path d="M19 15v-4h14v4"/></g><circle cx="5" cy="3" r="1.3" fill="currentColor"/><circle cx="47" cy="3" r="1.3" fill="currentColor"/></svg>}
export function Avatar({user={},size=36,online=false}) {const name=user.name||user.username||'?';return <span className="avatar-wrap" style={{width:size,height:size}}><span className="avatar" style={{width:size,height:size,fontSize:size*.34}}><span className="avatar-initials">{name.split(' ').map(n=>n[0]).slice(0,2).join('')}</span>{user.avatar&&<img src={user.avatar} alt={name} onError={e=>{e.currentTarget.style.display='none';}}/>}</span>{online&&<i className="presence-dot"/>}</span>}
export function CategoryIcon({category,size=22}) {const Icon=({courses:BookOpen,exercises:FolderOpen,exams:FileText,rattrapage:GraduationCap,general:FileText})[category]||BookOpen;return <span className={`category-icon ${category}`}><Icon size={size} strokeWidth={1.65}/></span>}
export function Badge({children,tone=''}) {return <span className={`badge ${tone}`}>{children}</span>}
export function PageHeading({eyebrow,title,description,children}) {return <header className="page-heading"><div>{eyebrow&&<span className="section-label">{eyebrow}</span>}<h1>{title}</h1>{description&&<p>{description}</p>}</div>{children&&<div className="page-heading-actions">{children}</div>}</header>}
export function EmptyState({icon:Icon=Inbox,title,description,action}) {return <div className="empty-state"><span className="empty-icon"><Icon size={30} strokeWidth={1.2}/></span><h3>{title}</h3>{description&&<p>{description}</p>}{action}</div>}
export function ResourceCard({resource:r,compact=false}) {const{t,lang,openModal,saved,toggleSave,toast}=useApp(); const isSaved=saved.some(s=>s.type==='resource'&&String(s.id)===String(r.id));return <article id={`resource-${r.id}`} className={`resource-card panel ${compact?'compact':''}`}>
  {!compact&&<button className={`resource-preview ${r.category}`} onClick={()=>openModal('preview',r)} aria-label={t('open','Ouvrir')+' '+r.title}><div className="paper-preview"><div className="paper-brand"><BrandMark size={15}/><span>USMBA · FPT TAZA</span></div><div className="paper-rule"/><b>{r.module||r.title}</b><span>{r.title}</span><i/><i/><i/><i/></div><span className="pdf-label">{fileLabel(r)}</span>{r.status&&<Badge tone={r.category}>{t(r.status,r.status==='new'?'Nouveau':r.status==='popular'?'Populaire':r.status==='corrected'?'Corrigé':'Mis à jour')}</Badge>}</button>}
  <div className="resource-body"><div className="resource-title-row"><CategoryIcon category={r.category} size={19}/><button className={`icon-button save-button ${isSaved?'is-saved':''}`} onClick={()=>toggleSave('resource',r.id).catch(e=>toast(e.message,'error'))} aria-label={t(isSaved?'unsave':'save',isSaved?'Retirer des enregistrés':'Enregistrer')}><Bookmark size={17} fill={isSaved?'currentColor':'none'}/></button></div><Link className="resource-title" to={resourcePath(r)} onClick={()=>openModal('preview',r)}>{r.title}</Link><div className="resource-meta"><span>{r.semester?`S${r.semester}`:t('general','Général')}</span><span>·</span><span>{r.module||t(r.category,categoryNames[r.category])}</span></div><div className="resource-author"><Avatar user={r.author} size={22}/><span>{r.author?.name||r.author?.username}</span>{r.author?.role?.includes('admin')&&<ShieldCheck size={13} className="gold"/>}<span className="resource-date">{formatDate(r.created_at,lang)}</span></div><div className="resource-card-bottom"><span><FileText size={12}/>{formatBytes(r.size||0,lang)}</span><span><Download size={12}/>{r.downloads||0}</span><span><Eye size={12}/>{r.views||0}</span></div><div className="resource-actions"><button className="subtle-link" onClick={()=>openModal('preview',r)}>{t('open','Ouvrir')}<ArrowUpRight size={14}/></button>{r.message_id&&<Link className="subtle-link" to={messagePath(r)}>{t('viewDiscussion','Voir la discussion')}<MessageSquare size={13}/></Link>}</div></div>
</article>}
export function Skeleton({rows=4}) {return <div className="skeleton-list" aria-busy="true">{Array.from({length:rows},(_,i)=><div className="skeleton" key={i}/>)}</div>}
export function VerifiedBadge(){const{t}=useApp();return <span className="verified-badge"><ShieldCheck size={13}/>{t('official','Officiel')}</span>}
