import assert from 'node:assert/strict';
import {chromium,expect} from '@playwright/test';
import {browserOptions,selectLanguage} from './browser-utils.mjs';
import {resourcePath,messagePath} from '../src/utils.js';
const origin=process.env.CAMPUS_BROWSER_ORIGIN||'http://localhost:5173';
const browser=await chromium.launch(browserOptions());
const admin=await browser.newContext();
const student=await browser.newContext({viewport:{width:1440,height:1000}});
const page=await student.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const report=message=>console.log('PASS '+message);
async function get(context,path){const r=await context.request.get(origin+'/api'+path);assert.ok(r.ok(),`${path}: ${r.status()}`);return r.json();}
try{
  await admin.request.post(origin+'/api/login',{data:{username:'admin',password:'Admin2026!'}});
  await page.goto(origin+'/');
  await page.locator('.hero-copy h1').waitFor();
  assert.equal(await page.locator('html').getAttribute('lang'),'fr');
  assert.equal(await page.locator('input[type=password]').count(),0);
  await selectLanguage(page,'AR');
  await expect(page.locator('html')).toHaveAttribute('dir','rtl');
  assert.ok((await page.locator('.hero-copy h1').textContent()).includes('مجتمع'));
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await selectLanguage(page,'EN');
  await expect(page.locator('html')).toHaveAttribute('dir','ltr');
  await selectLanguage(page,'FR');
  report('first visit welcome and complete FR/AR/EN direction switching');

  await page.goto(origin+'/login');
  await page.locator('input[autocomplete=username]').fill('unknown');
  await page.locator('input[autocomplete=current-password]').fill('Wrong2026!');
  await page.locator('.login-form-wrap form >button').click();
  await page.locator('.form-error').waitFor();
  assert.equal(await page.getByRole('button',{name:/switch account/i}).count(),0);
  await page.locator('.forgot-link').click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('dialog').getByLabel('Nom complet',{exact:true}).fill('Ismail');
  await page.getByRole('dialog').getByLabel('E-mail de contact',{exact:true}).fill('ismail@example.ma');
  await page.getByRole('dialog').getByLabel('Votre message',{exact:true}).fill('Test automatisé : aide pour les identifiants.');
  await page.getByRole('dialog').locator('form >button').click();
  await page.locator('.modal-success').waitFor();
  assert.ok((await get(admin,'/admin')).contacts.some(c=>c.subject==='credentials'));
  await page.keyboard.press('Escape');
  report('login validation and stored administrator credential-recovery request');

  await page.locator('input[autocomplete=username]').fill('ismail');
  await page.locator('input[autocomplete=current-password]').fill('Campus2026!');
  await page.locator('.login-form-wrap form >button').click();
  await page.waitForURL('**/onboarding/faculty');
  await expect(page.locator('.faculty-choice')).toHaveCount(4);
  await expect(page.locator('.onboarding >button')).toBeDisabled();
  await page.locator('.faculty-choice').first().click();
  await expect(page.locator('.onboarding >button')).toBeDisabled();
  await page.locator('.faculty-confirmation input').check();
  await page.locator('.onboarding >button').click();
  await page.waitForURL('**/onboarding/studies');
  await expect(page.locator('.faculty-choice')).toHaveCount(0);
  await page.locator('#setup-filiere').selectOption({label:'مسلك الدراسات الفرنسية (S1, S3, S5)'});
  await page.locator('#setup-semester').selectOption('1');
  await page.locator('.studies-selection-form').getByRole('button',{name:'Compléter mon compte',exact:true}).click();
  await page.waitForURL('**/app');
  await page.locator('.study-welcome h1').waitFor();
  assert.equal((await get(student,'/bootstrap')).faculty.id,'flaa');
  assert.equal((await get(student,'/bootstrap')).user.filiere_id,'french_studies');
  assert.equal((await get(student,'/bootstrap')).user.current_semester,1);
  assert.equal(await page.locator('.faculty-sidebar').getByText('FEG',{exact:true}).count(),0);
  await page.goto(origin+'/onboarding/faculty');await page.waitForURL('**/app');
  await page.reload();await page.locator('.study-welcome h1').waitFor();
  const cookie=(await student.cookies()).find(c=>c.name==='campus_session');assert.ok(cookie.httpOnly);assert.equal(cookie.sameSite,'Lax');
  assert.equal((await student.request.get(origin+'/api/bootstrap?faculty_id=feg')).status(),403);
  report('confirmed faculty followed by own-faculty filière setup, permanent route guard, refresh persistence and faculty isolation');

  await page.goto(origin+'/app/chat/general');
  await page.locator('.chat-message').first().waitFor();
  const notificationsBefore=(await get(admin,'/bootstrap')).notifications.length;
  const chatText='E2E communauté : une question sur le commentaire composé.';
  await page.locator('.chat-composer textarea').fill(chatText);
  await page.locator('.composer-send').click();
  const message=page.locator('.chat-message').filter({has:page.locator('.message-text').filter({hasText:chatText})}).last();
  await message.waitFor();
  await expect(page.locator('.chat-composer textarea')).toHaveValue('');
  assert.equal((await get(admin,'/bootstrap')).notifications.length,notificationsBefore);
  await message.getByRole('button',{name:/J.aime/}).click();
  await expect(message.locator('.reaction.like')).toHaveAttribute('aria-pressed','true');
  await message.hover();await message.getByRole('button',{name:'Enregistrer',exact:true}).click();
  assert.ok((await get(student,'/bootstrap')).saved.some(s=>s.type==='message'));
  await message.hover();await message.getByRole('button',{name:'Répondre',exact:true}).first().click();
  await page.locator('.composer-reply').waitFor();
  await page.locator('.chat-composer textarea').fill('E2E réponse liée au message original.');await page.locator('.composer-send').click();
  await page.locator('.reply-context').filter({hasText:chatText.slice(0,30)}).waitFor();
  report('live chat send, no general notifications, reaction, bookmark and threaded reply');

  const file={name:'notes-e2e.txt',mimeType:'text/plain',buffer:Buffer.from('Notes E2E de commentaire composé. Introduction, problématique, axes et citations.')};
  const beforeUpload=(await get(student,'/bootstrap')).resources.length;
  await page.locator('.chat-composer input[type=file]').setInputFiles(file);
  await page.getByRole('dialog').waitFor();
  assert.equal((await get(student,'/bootstrap')).resources.length,beforeUpload,'File is not sent before classification');
  await expect(page.getByRole('dialog').getByLabel('Filière',{exact:true})).toHaveValue('french_studies');
  assert.equal(await page.getByRole('dialog').getByRole('combobox',{name:/faculté/i}).count(),0,'Upload reuses faculty without asking again');
  await page.getByRole('dialog').getByLabel('Type de contenu',{exact:true}).selectOption('exercises');
  await page.getByRole('dialog').getByLabel('Semestre',{exact:true}).selectOption('3');
  await page.getByRole('dialog').getByLabel('Module',{exact:true}).fill('Analyse de texte');
  await page.getByRole('dialog').getByLabel('Titre de la ressource',{exact:true}).fill('E2E Notes classées');
  await page.getByRole('dialog').locator('form >button').click();
  await page.getByRole('dialog').waitFor({state:'hidden'});
  const bootstrap=await get(student,'/bootstrap');const resource=bootstrap.resources.find(r=>r.title==='E2E Notes classées');assert.ok(resource);assert.equal(resource.semester,3);assert.equal(resource.category,'exercises');
  assert.equal(resource.filiere_id,'french_studies');
  assert.equal(bootstrap.messages.find(m=>m.id===resource.message_id).semester,null,'Resource S3 classification does not split the faculty general chat');
  assert.equal(resource.chat_semester,null,'General chat uploads do not require a chat semester');
  assert.equal(bootstrap.messages.find(m=>m.id===resource.message_id).resource_id,resource.id);
  await page.locator(`#message-${resource.message_id}`).locator('.attachment-location').click();
  await page.waitForURL(`**/app/resources/exercises/s3/analyse-de-texte#resource-${resource.id}`);
  await page.locator(`#resource-${resource.id}`).waitFor();
  await page.reload();await page.locator(`#resource-${resource.id}`).waitFor();
  await page.locator(`#resource-${resource.id}`).getByRole('link',{name:'Voir la discussion',exact:true}).click();
  await page.waitForURL('**'+messagePath(resource));
  await page.locator(`#message-${resource.message_id}.deep-focus`).waitFor();
  report('file classification before upload, shared object, semester/module and bidirectional deep links');

  await page.locator('.chat-composer input[type=file]').setInputFiles(file);
  await page.getByRole('dialog').waitFor();
  await page.getByRole('dialog').getByLabel('Type de contenu',{exact:true}).selectOption('exercises');
  await page.getByRole('dialog').getByLabel('Module',{exact:true}).fill('Analyse de texte');
  await page.getByRole('dialog').locator('form >button').click();
  await page.getByRole('dialog').locator('.form-error').waitFor();
  await page.getByRole('dialog').getByRole('link',{name:'Voir la ressource existante'}).waitFor();
  assert.equal((await get(student,'/bootstrap')).resources.length,beforeUpload+1);
  await page.keyboard.press('Escape');
  report('duplicate file detection preserves one physical upload');

  await page.keyboard.press('Control+k');await page.getByRole('dialog').waitFor();
  await page.locator('.command-input input').fill('E2E Notes classées');
  await page.locator('.command-result').first().waitFor();
  await page.locator('.command-input input').press('Enter');
  await page.waitForURL(`**#resource-${resource.id}`);
  await page.locator(`#resource-${resource.id}`).getByRole('button',{name:'Ouvrir',exact:true}).click();
  await page.getByRole('dialog').waitFor();await page.locator('.preview-actions').getByRole('button',{name:'Signaler',exact:true}).click();
  await page.getByRole('dialog').getByLabel('Motif',{exact:true}).selectOption('classification');
  await page.getByRole('dialog').locator('form >button').click();await page.getByRole('dialog').waitFor({state:'hidden'});
  assert.ok((await get(admin,'/admin')).reports.some(r=>r.target_id===resource.id&&r.reason==='classification'));
  report('keyboard command search opens exact resource and report reaches moderation');

  const pinned=await admin.request.post(origin+`/api/messages/${resource.message_id}/pin`);assert.ok(pinned.ok());
  const announcements=(await get(student,'/bootstrap')).announcements;const a=announcements.find(a=>a.message_id===resource.message_id);assert.ok(a);assert.equal(a.resource_id,resource.id);assert.equal(a.author.id,bootstrap.user.id);
  await page.goto(origin+'/app/announcements#announcement-'+a.id);await page.locator('#announcement-'+a.id).waitFor();
  await page.locator('#announcement-'+a.id+' .announcement-footer a').click();await page.waitForURL(`**#message-${resource.message_id}`);
  await page.goto(origin+'/app/chat/important');await page.locator('.chat-composer textarea').fill('E2E discussion importante : rendez-vous de révision.');await page.locator('.composer-send').click();
  await page.locator('.message-text').filter({hasText:'E2E discussion importante'}).waitFor();
  assert.ok((await get(admin,'/bootstrap')).notifications.some(n=>n.type==='important'&&n.body.includes('E2E discussion')));
  report('pinned announcement preserves author/source/attachment and important chat notifies');

  const arabicUpload=await student.request.post(origin+'/api/uploads',{multipart:{file:{name:'arabic-notes.txt',mimeType:'text/plain',buffer:Buffer.from('التحليل الأدبي: مقدمة وإشكالية وخاتمة.')},title:'E2E Notes arabes',category:'courses',semester:'4',module:'التحليل الأدبي',filiere_id:'french_studies',resource_type:'courses',channel:'general',content:'E2E Module en arabe.'}});
  assert.ok(arabicUpload.ok());const arabicResource=(await arabicUpload.json()).resource;
  await page.goto(origin+resourcePath(arabicResource));await page.locator(`#resource-${arabicResource.id}`).waitFor();
  await page.locator(`#resource-${arabicResource.id}`).getByRole('button',{name:'Ouvrir',exact:true}).click();
  await page.locator('.text-document').filter({hasText:'التحليل الأدبي'}).waitFor();await page.keyboard.press('Escape');
  report('Arabic module deep links and real text document preview');
  await page.setViewportSize({width:390,height:844});await page.goto(origin+'/app/chat/general');await page.locator('.chat-composer').waitFor();
  await page.locator('.mobile-menu').click();await page.locator('.navigation-columns.drawer-open').waitFor();
  await page.locator('.drawer-top').first().getByRole('button',{name:'Fermer',exact:true}).click();
  await selectLanguage(page,'AR');
  await expect(page.locator('html')).toHaveAttribute('dir','rtl');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.setViewportSize({width:834,height:1112});await page.locator('.mobile-menu').click();await page.locator('.navigation-columns.drawer-open').waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  report('mobile and tablet drawers, Arabic RTL chat and zero browser runtime errors');
}catch(error){console.log('FAILED COMMUNITY PAGE',page.url(),await page.locator('body').innerText());console.log('RUNTIME ERRORS',errors);await page.screenshot({path:'/tmp/campuslink-community-test-failure.png'});throw error;}finally{await browser.close();}
