CREATE TABLE faculties (
  id TEXT PRIMARY KEY, code TEXT NOT NULL, name TEXT NOT NULL, arabic TEXT NOT NULL,
  description TEXT NOT NULL, icon TEXT NOT NULL, color TEXT NOT NULL, members INTEGER DEFAULT 0
);
CREATE TABLE filieres (
  id TEXT PRIMARY KEY, faculty_id TEXT NOT NULL REFERENCES faculties(id), name TEXT NOT NULL,
  UNIQUE (id, faculty_id)
);
CREATE TABLE semesters (id INTEGER PRIMARY KEY CHECK (id BETWEEN 1 AND 6), name TEXT NOT NULL);
CREATE TABLE users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id TEXT UNIQUE, email TEXT, username TEXT NOT NULL, name TEXT NOT NULL,
  avatar TEXT NOT NULL DEFAULT '', avatar_object_key TEXT, role TEXT NOT NULL DEFAULT 'student',
  faculty_id TEXT REFERENCES faculties(id), filiere_id TEXT REFERENCES filieres(id),
  current_semester INTEGER NOT NULL DEFAULT 1 REFERENCES semesters(id),
  language TEXT NOT NULL DEFAULT 'fr',
  preferences TEXT NOT NULL DEFAULT '{"resources":true,"announcements":true,"important":true,"admin":true,"calendar":true}',
  disabled INTEGER NOT NULL DEFAULT 0, last_seen TEXT,
  session_version INTEGER NOT NULL DEFAULT 0, auth_revoked_at TEXT, legacy_password_hash TEXT,
  FOREIGN KEY (filiere_id, faculty_id) REFERENCES filieres(id, faculty_id)
);
CREATE UNIQUE INDEX users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX users_email_lower ON users (lower(email)) WHERE email IS NOT NULL;
CREATE TABLE modules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT NOT NULL REFERENCES faculties(id), filiere_id TEXT REFERENCES filieres(id),
  semester INTEGER REFERENCES semesters(id), name TEXT NOT NULL,
  UNIQUE NULLS NOT DISTINCT (faculty_id, filiere_id, semester, name),
  FOREIGN KEY (filiere_id, faculty_id) REFERENCES filieres(id, faculty_id)
);
CREATE TABLE messages (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT REFERENCES faculties(id), channel TEXT NOT NULL, content TEXT NOT NULL,
  author_id INTEGER REFERENCES users(id), created_at TEXT NOT NULL, resource_id INTEGER,
  reply_to INTEGER REFERENCES messages(id) DEFERRABLE INITIALLY DEFERRED,
  pinned INTEGER NOT NULL DEFAULT 0, removed INTEGER NOT NULL DEFAULT 0,
  filiere_id TEXT REFERENCES filieres(id), semester INTEGER REFERENCES semesters(id),
  FOREIGN KEY (filiere_id, faculty_id) REFERENCES filieres(id, faculty_id)
);
CREATE INDEX message_faculty ON messages(faculty_id);
CREATE INDEX message_studies ON messages(faculty_id,channel,filiere_id,semester);
CREATE TABLE resources (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT REFERENCES faculties(id), title TEXT NOT NULL, filename TEXT NOT NULL,
  object_key TEXT NOT NULL, stored_name TEXT NOT NULL DEFAULT '', sha256 TEXT NOT NULL,
  category TEXT NOT NULL, semester INTEGER REFERENCES semesters(id),
  module_id INTEGER REFERENCES modules(id), module TEXT NOT NULL DEFAULT '',
  author_id INTEGER REFERENCES users(id), created_at TEXT NOT NULL, size INTEGER NOT NULL,
  mime TEXT NOT NULL, downloads INTEGER NOT NULL DEFAULT 0, views INTEGER NOT NULL DEFAULT 0,
  message_id INTEGER REFERENCES messages(id) DEFERRABLE INITIALLY DEFERRED,
  channel TEXT NOT NULL DEFAULT 'general', status TEXT NOT NULL DEFAULT 'new',
  version INTEGER NOT NULL DEFAULT 1, removed INTEGER NOT NULL DEFAULT 0,
  filiere_id TEXT REFERENCES filieres(id), resource_type TEXT NOT NULL DEFAULT '',
  FOREIGN KEY (filiere_id, faculty_id) REFERENCES filieres(id, faculty_id)
);
ALTER TABLE messages ADD CONSTRAINT message_resource FOREIGN KEY (resource_id) REFERENCES resources(id) DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX resource_faculty ON resources(faculty_id);
CREATE INDEX resource_studies ON resources(faculty_id,filiere_id,semester,module_id);
CREATE TABLE resource_versions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id INTEGER REFERENCES resources(id), version INTEGER,
  filename TEXT, object_key TEXT NOT NULL, stored_name TEXT NOT NULL DEFAULT '',
  sha256 TEXT, size INTEGER, mime TEXT, updated_at TEXT, editor_id INTEGER REFERENCES users(id)
);
CREATE TABLE reactions (
  message_id INTEGER REFERENCES messages(id), user_id INTEGER REFERENCES users(id), reaction TEXT,
  PRIMARY KEY(message_id,user_id,reaction)
);
CREATE TABLE announcements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT REFERENCES faculties(id), content TEXT NOT NULL,
  message_id INTEGER UNIQUE REFERENCES messages(id), channel TEXT NOT NULL DEFAULT 'general',
  author_id INTEGER REFERENCES users(id), created_at TEXT NOT NULL, resource_id INTEGER,
  pinned INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE notifications (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE, faculty_id TEXT REFERENCES faculties(id),
  type TEXT NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, path TEXT NOT NULL,
  created_at TEXT NOT NULL, read INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE events (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT REFERENCES faculties(id), title TEXT NOT NULL, date TEXT NOT NULL,
  time TEXT NOT NULL, type TEXT NOT NULL
);
CREATE TABLE channels (
  id TEXT NOT NULL, faculty_id TEXT REFERENCES faculties(id), name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '', read_only INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY(id,faculty_id)
);
CREATE TABLE saved (
  user_id INTEGER REFERENCES users(id), type TEXT, target_id INTEGER,
  PRIMARY KEY(user_id,type,target_id)
);
CREATE TABLE history (
  user_id INTEGER REFERENCES users(id), resource_id INTEGER REFERENCES resources(id),
  opened_at TEXT NOT NULL, PRIMARY KEY(user_id,resource_id)
);
CREATE TABLE reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT REFERENCES faculties(id), reporter_id INTEGER REFERENCES users(id),
  target_type TEXT NOT NULL, target_id INTEGER NOT NULL, reason TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'open', created_at TEXT NOT NULL
);
CREATE TABLE contacts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  faculty_id TEXT REFERENCES faculties(id), user_id INTEGER REFERENCES users(id), name TEXT,
  email TEXT, subject TEXT NOT NULL, message TEXT NOT NULL, created_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open'
);
CREATE TABLE legacy_imports (
  source_sha256 TEXT PRIMARY KEY, row_counts JSONB NOT NULL, imported_at TEXT NOT NULL
);
