import {slug} from '../shared/paths.js';
export {slug};
export const resourcePath = r => `/app/resources/${r.category}${r.semester ? `/s${r.semester}` : ''}${r.module ? `/${slug(r.module)}` : ''}#resource-${r.id}`;
export const messagePath = m => `/app/chat/${m.channel || 'general'}#message-${m.message_id || m.id}`;
export const formatBytes = (size,lang='fr') => {const large=size>=1048576;const units=({fr:['Ko','Mo'],en:['KB','MB'],ar:['كيلوبايت','ميغابايت']})[lang]||['KB','MB'];return `${new Intl.NumberFormat(lang,{maximumFractionDigits:large?1:0}).format(large?size/1048576:Math.ceil(size/1024))} ${units[large?1:0]}`;};
export const formatDate = (date, lang = 'fr', options = {}) => new Intl.DateTimeFormat(lang === 'ar' ? 'ar-MA' : lang === 'en' ? 'en-GB' : 'fr-FR', {day:'numeric', month:'short', timeZone:'Africa/Casablanca', ...options}).format(new Date(date));
export const categoryKeys = ['courses', 'exercises', 'exams', 'rattrapage'];
export const categoryNames = { courses: 'Cours', exercises: 'Exercices', exams: 'Anciens examens', rattrapage: 'Rattrapage', general: 'Document général' };
export const fileLabel = resource => resource.mime?.startsWith('image/') ? 'IMG' : resource.mime === 'application/pdf' ? 'PDF' : resource.mime === 'text/plain' ? 'TXT' : resource.filename?.split('.').pop()?.toUpperCase().slice(0,4) || 'DOC';
export const roleNames = { student: 'Étudiant', moderator: 'Modérateur', faculty_admin: 'Administrateur', global_admin: 'Administrateur global' };
